-- Database: sdc

-- DROP DATABASE IF EXISTS sdc;

CREATE DATABASE IF NOT EXISTS sdc
    WITH
    OWNER = jonathanghee
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT TEMPORARY, CONNECT ON DATABASE sdc TO PUBLIC;

GRANT ALL ON DATABASE sdc TO jonathanghee;

-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS cart
(
    id integer NOT NULL,
    user_session character varying COLLATE pg_catalog."default",
    prod_id character varying COLLATE pg_catalog."default",
    active character varying COLLATE pg_catalog."default",
    CONSTRAINT cart_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS features
(
    id integer NOT NULL,
    product_id integer,
    value character varying COLLATE pg_catalog."default",
    feature character varying COLLATE pg_catalog."default",
    CONSTRAINT features_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS photos
(
    id integer NOT NULL,
    style_id integer,
    url character varying COLLATE pg_catalog."default",
    thumbnail_url character varying COLLATE pg_catalog."default",
    CONSTRAINT photos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product
(
    id integer NOT NULL,
    name character varying COLLATE pg_catalog."default",
    slogan character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    category character varying COLLATE pg_catalog."default",
    default_price character varying COLLATE pg_catalog."default",
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS related
(
    id integer NOT NULL,
    current integer,
    related integer,
    CONSTRAINT related_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS skus
(
    id integer NOT NULL,
    style_id integer,
    size character varying COLLATE pg_catalog."default",
    quantity smallint,
    CONSTRAINT pk_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS styles
(
    style_id integer NOT NULL,
    prod_id integer,
    name character varying COLLATE pg_catalog."default",
    sale_price character varying COLLATE pg_catalog."default",
    original_price character varying COLLATE pg_catalog."default",
    default_style boolean,
    CONSTRAINT styles_pkey PRIMARY KEY (style_id)
);

ALTER TABLE IF EXISTS features
    ADD CONSTRAINT fk_prod_id FOREIGN KEY (product_id)
    REFERENCES product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS photos
    ADD CONSTRAINT fk_style_id FOREIGN KEY (style_id)
    REFERENCES styles (style_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS related
    ADD CONSTRAINT fk_curr FOREIGN KEY (current)
    REFERENCES product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS skus
    ADD CONSTRAINT fk_style_id FOREIGN KEY (style_id)
    REFERENCES styles (style_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS styles
    ADD CONSTRAINT fk_prod_id FOREIGN KEY (prod_id)
    REFERENCES product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;